# Generated by Django 3.1.3 on 2021-01-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_extra', models.CharField(blank=True, max_length=20, null=True, verbose_name='Описание для робота')),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.image', verbose_name='Фото'),
        ),
    ]
