# Generated by Django 3.1.3 on 2021-01-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210125_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='images',
        ),
        migrations.AddField(
            model_name='actor',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Image', verbose_name='Фото'),
        ),
    ]
