# Generated by Django 3.1.3 on 2021-01-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='lenth',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Продолжительность (мин)'),
            preserve_default=False,
        ),
    ]
